kind: service
name: hypershell-gateway-console
archetype: hypershell-gateway-browser
language: go
overrides:
  postgres-adapter:
    migrations: external
  browser-telemetry:
    service_name: hypershell-gateway-console
  health-check:
    database: true
  browser-backend:
    dynamic_styles: true
    telemetry_service_name: hypershell-gateway-console
    logout_scope: identity_provider
    api_prefix: /api/v1
    routes: ["/", "/gateway", "/global-policy", "/settings", "/workspaces", "/workspaces/{id}", "/workspaces/{id}/sandboxes/{id}", "/workspaces/{id}/providers/{id}"]
    asset_bundle: ui/build.zip
  kubernetes-service:
    local_applications:
      - port: 8000
        image: ghcr.io/jsell-rh/hypershell-stego-dashboard-ci@sha256:6cec0376ab3f48d2b3da085237ae940cc7a6b34f4a72e515865e99ea0f90d7bb
        listen_env: LISTEN_ADDRESS
        port_env: PORT
        env_secret: dashboard-application-env
        files_secret: dashboard-application-files
        health_path: /api/v1/readyz
